# Generated by Django 5.0.7 on 2024-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_myaudiofile_myaudio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaudiofile',
            name='myaudio_url',
        ),
        migrations.AddField(
            model_name='myaudiofile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
